### ISSUE TITLE
Dropdown-Menü bei großer Benutzeranzahl im Board überfordert

### ISSUE THREAD

**Issue by Crizz0** [Crizz0/contactadmin#1]
Austausch des Dropdown in den Einstellungen für "Kontaktbot-Benutzer" mit einem Inputfeld für User-ID oder Benutzername

Keine Auswahl und gleichzeitig "Kontaktbot-Benutzer als Beitragsersteller:" führt zu einem Fehler, wenn der Kontaktbot genutzt werden soll.

**Comment by LukeWCS** [comment]
Hey Chris

Hast du da schon was in Arbeit? Ansonsten könnte ich mir das mal anschauen, ich hätte bereits eine Idee wie man das ordentlich lösen könnte, indem man einfach die Benutzer-Auswahl von phpBB nachbaut. Dann ist es auch völlig irrelevant ob ein Board 10 oder 10000 User hat. ^^

**Comment by Crizz0** [comment]
Ne, noch nichts in Planung.

Ich dschte einfach an so ein Benutzer-Inputfeld wie im ACP bei Benutzer suchen oder so.

**Comment by LukeWCS** [comment]
Beides. ^^ Man kann dann entweder einfach einen Namen eingeben, oder mit der komfortablen Benutzersuche von phpBB arbeiten. 

Dann schau ich mir das mal an.
