### ISSUE TITLE
Kleiner Fehler in den Sprachdateien verursacht eine falsche URL

### ISSUE THREAD

**Issue by LukeWCS** [Crizz0/contactadmin#2]
Hi Chris

Ich hatte dich schon 2018 mal darauf hingewiesen, ist aber vermutlich in Vergessenheit geraten. Ich habe jetzt auch ne Weile gebraucht, das wiederzufinden. ^^

https://www.phpbb.de/community/viewtopic.php?p=1385697#p1385697

Fehlermeldungen:

```
[phpBB Debug] PHP Notice: in file [ROOT]/ext/rmcgirr83/contactadmin/language/de/contact.php on line 70: Undefined variable: phpbb_root_path
[phpBB Debug] PHP Notice: in file [ROOT]/ext/rmcgirr83/contactadmin/language/de/contact.php on line 70: Undefined variable: phpEx
```

Ursache:

Nicht definierte Variablen `$phpbb_root_path` und `$phpEx` in der Sprachdatei `contact.php`:

https://github.com/Crizz0/contactadmin/blob/3.2.x/language/de/contact.php#L70

**Comment by Crizz0** [comment]
Ja, da brauchst einen Platzhalter in der Sprachvariable und nicht den Link direkt. 

Am 13. Februar 2020 15:05:27 MEZ schrieb LukeWCS <notifications@github.com>:
